import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='ja'>
      <body>
        <header>
          <Link className='text-blue-600 underline hover:no-underline m-4' href='/'>
            Home
          </Link>
          <Link className='text-blue-600 underline hover:no-underline m-4' href='/MyPage'>
            MyPage
          </Link>
        </header>
        <main className='container p-3 m-3'>{children}</main>
      </body>
    </html>
  )
}
